spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.12.159.50:3306/puhaocar
    username: huahua
    password: 4582425
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在的路径
  type-aliases-package: com.xa.pojo                  # 所有pojo别名类所在的包
  mapper-locations:
    - classpath:mapper/*.xml                  #mapper映射文件